# Generated by Django 3.2.5 on 2022-01-06 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Kathmandu', 'Kathmandu')], default='Kathmandu', max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('phone_no', models.PositiveBigIntegerField()),
                ('house_no', models.PositiveIntegerField()),
                ('zip_code', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
